name             'cs-chef-tnt'
license          'All rights reserved'
description      'Installs/Configures cs-chef-tnt'
version          '0.1.0'

depends 'chocolatey', '~> 1.2.0'
depends 'powershell'
depends 'seven_zip'
depends 'aws'
depends 'sql_server'
depends 'monitor'
depends 'windows' , '< 5.0.0'
